id: P004445
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18772
  title: གྲོང་གསེབ་ཀྱི་ཏང་རྩ་འཛུགས་འཛུགས་སྐྱོང་བྱེད་ཕྱོགས།
  author: ''
  volumes:
    56e2d754908f45caa02153c2e7b797f2:
      image_group_id: I8LS18774
      title: ''
      volume_number: 1
      total_pages: 419
      base_file: v001.txt
